Add FreeBSD support

diff --git a/mx b/mx
--- a/mx
+++ b/mx
@@ -46,27 +46,16 @@ if [ -n "${MX_PYTHON}" ]; then
 elif [ -n "${MX_PYTHON_VERSION}" ]; then
     python_exe=python${MX_PYTHON_VERSION}
 else
-    type python3.8 >/dev/null 2>&1
-    if [ $? -eq 0 ]; then
-        python_exe=python3.8
-    else
-        type python3 >/dev/null 2>&1
+    for candidate in python3.8 python3 python3.14 python3.13 python3.12 python3.11 python3.10 python3.9 python; do
+        type ${candidate} >/dev/null 2>&1
         if [ $? -eq 0 ]; then
-            python_exe=python3
-        else
-            type python > /dev/null 2>&1
-            if [ $? -eq 0 ]; then
-                python_exe=python
-            else
-                type python3 > /dev/null 2>&1
-                if [ $? -eq 0 ]; then
-                    python_exe=python3
-                else
-                    echo "Cannot find Python on PATH"
-                    exit 1
-                fi
-            fi
+            python_exe=${candidate}
+            break
         fi
+    done
+    if [ -z "${python_exe}" ]; then
+        echo "Cannot find Python on PATH"
+        exit 1
     fi
 fi
 
